### ISSUE TITLE
Improvement idea - GetHashCode inside Equals

### ISSUE THREAD

**Issue by FrantisekBodnar** [xaviergonz/T4Immutable#3]
Hi,
I have to say it is great idea that you have created this T4, it is very helpful and saved me lot of code to write. :) 

What I found is, that you can improve a performance in Equals method by adding in generated method **ImmutableEquals** by adding **this.GetHashCode().Equals(obj.GetHashCode())** as first code in return statement, before **T4Immutable.Helpers.AreEqual** for each property. 

Because by Microsoft specification,:
https://msdn.microsoft.com/en-us/library/system.object.gethashcode(v=vs.110).aspx
> A hash function must have the following properties:
> _**If two objects compare as equal, the GetHashCode method for each object must return the same value.** However, if two objects do not compare as equal, the GetHashCode methods for the two objects do not have to return different values._
> 

**You will be sure, that these two object are same and also it is faster to compare two integers first, and than all properties**  

What do you think?

Thanks
Frankie

**Comment by xaviergonz** [comment]
Nice idea :) Implemented in 1.3.3 as:
```
if (ImmutableGetHashCode() !== obj.ImmutableGetHashCode()) return false;
```
still need to check if the properties are the same if the hash codes match though due to possible hash collisions.
