### ISSUE TITLE
Support for Nullable Properties?

### ISSUE THREAD

**Issue by michaeltnguyen** [xaviergonz/T4Immutable#6]
Hi,

Awesome library by the way.  It's reminiscent of Google's [AutoValue](https://github.com/google/auto/tree/master/value). 

How could we go about adding support for nullable properties?  Right now, using the `Builder` class requires non-null properties, but the regular constructor supports nullables.  Ideally we'd add an attribute for `[Nullable]`, which then affects the Builder code emitted at https://github.com/xaviergonz/T4Immutable/blob/master/src/content/T4Immutable/T4Immutable.tt#L421.  It looks like everything else (Helpers and OptParam) already support nulls.

I can work on the PR, just wanted to make sure you agree with the approach.

Michael

**Comment by xaviergonz** [comment]
Hey! thanks for your interest. By nullable you mean nullable structs, integers, etc I presume? do you have an example of the class you are trying to make immutable?

**Comment by michaeltnguyen** [comment]
Yep, the most common use for us is a nullable string.  For example:

```
class Person {
  public string LastName { get; } // must not be null

  [Nullable]
  public string MiddleName { get; } // can be null
}
```

Right now the auto-generated builder code is:
```
public Person Build() {
  if (!this.LastName.HasValue) throw new InvalidOperationException();
  if (!this.MiddleName.HasValue) throw new InvalidOperationException(); // doh, cannot be null
}
```

**Comment by xaviergonz** [comment]
Just wondering, did you try to actually set MiddleName to null on the builder instead of just omitting it?
E.g.
```
var person = new Person.Builder().With(LastName: "Doe", MiddleName: null).Build();
```
or
```
var builder = new Person.Builder();
builder.LastName = "Doe";
builder.MiddleName = null;
const person = builder.Build();
```
Because in the generated builder code the properties are actually of type T4Immutable.OptParam<string>, so a call to .HasValue() in this context basically means "the property was given some value (even if that value is null)" rather than "the string itself has a value"

**Comment by michaeltnguyen** [comment]
Ah, I did not try that.  My bad, I assumed that `HasValue()` and `!= null` were equivalent.  Seems like we could also set null as the default value, a la:

```
const string MiddleNameDefaultValue = null;
```

For our particular use case, the value object has ~30 or so fields, only two of which are required, so I wanted to avoid `builder.With(Field1: null, Field2: null, ...)`, and I'm hoping the null default will solve that.

Having to assign default values to a bunch of fields is a little clunky, but I also think that "how fields should behave by default" is probably best left up to whoever's writing the value classes, and not the responsibility of the library.

Thank you for your help.  I think we can consider this closed.

**Comment by xaviergonz** [comment]
The null default should take care of it, yeah :)
Glad I could be of help!
